error: add a public method for constructing `Error` values
I've finally relented and exposes a very restricted way
to build an `Error` value.

I was motivated to do this because there are some traits
in Jiff that use `jiff::Error` in their return types. Without
a constructor like this, it isn't possible for implementors
of that trait to provide their own error values.