error: replace a few more instances of unnecessary `write!` calls
I missed these because I had filtered `src/error/` out of my search for
`write!` calls when looking for ones that could be removed. (Because
`src/error/` is where `write!` is most commonly needed.)