error: tighten up some error messages
This removes a bit of redundancy in existing error messages. For
example, instead of:

```
failed to parse hour in time: failed to parse two digit integer as hour: parameter 'hour' is not in the required range of 0..=23
```

We now have:

```
failed to parse two digit integer as hour: parameter 'hour' is not in the required range of 0..=23
```

Which is a little better.

Fixes #519