error: make Debug match Display
I'm kind of annoyed that an `Error`'s `Debug` impl shows the full
internal representation. In particular, this is something that *users*
of Jiff will see due to `unwrap()` and the like. So it makes sense to
tighten it up a bit. Jiff users don't need to care about the internal
error kind and what not.