error: faster builds via macro instead of trivial '?' ops
This commit introduces the `rtry!` macro and uses it throughout the
codebase instead of `?` for forwarding result types whose error types
are already same.

The de-sugared try operator ('?') invokes but the Try trait and
From trait, but for most of are error forwarding sites we need neither.

For rustc 1.94.0 (4a4ef493e 2026-03-02).

The total debug build `cargo llvm-lines` of the jiff,
reduced from 174096 to 168315 LLVM lines.

Measure the from 5 samples of `perf stat` on a direct rustc invocation to build
the jiff rlib, shows the following:

Before (using the try operator)
    10,889,052,814      cycles:u        ( +-  0.08% )
    15,171,370,701      instructions:u  ( +-  0.01% )
     2,671,428,910      branch:u        ( +-  0.01% )

    1.60105 +- 0.00152 seconds time elapsed  ( +-  0.09% )

After (using the macro)
    10,454,390,370      cycles:u        ( +-  0.12% )
    14,591,413,777      instructions:u  ( +-  0.01% )
     2,567,871,039      branch:u        ( +-  0.01% )

    1.55956 +- 0.00335 seconds time elapsed  ( +-  0.21% )

The above perf results show an improvement of 3-4% percent.